version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: aplatonovnet/streaming-api:latest
    container_name: streaming_api
    ports:
      - "5082:80" # host:container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ./Streaming/data:/app/data
    networks:
      - streaming-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/api/streaming/test || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  rtmp-server:
    build:
      context: .
      dockerfile: Dockerfile.rtmp
    image: aplatonovnet/streaming-rtmp:latest
    container_name: rtmp_server
    ports:
      - "1935:1935"
      - "8000:8000"
    environment:
      - DEV_MODE=false
      - API_URL=http://api:80
    volumes:
      - ./media:/usr/src/app/media
    depends_on:
      - api
    networks:
      - streaming-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  streaming-network:
    driver: bridge