listen              1935;
max_connections     1000;

daemon              off;
srs_log_tank       console;
srs_log_level      trace;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         on;
    listen          8000;
    dir             ./objs/nginx/html;
    crossdomain     on;
}

vhost __defaultVhost__ {
    # RTMP/HTTP-FLV config
    tcp_nodelay     on;
    min_latency     on;

    # Basic publish settings
    publish {
        mr          off;
        firstpkt_timeout    40000;
        normal_timeout      15000;
    }

    # Basic play settings
    play {
        gop_cache       on;
        queue_length    30;
        mw_latency     100;
        time_jitter    full;
    }

    # HTTP callbacks
    http_hooks {
        enabled         on;
        # Stream publishing hooks
        on_publish      http://host.docker.internal:5082/api/streaming/validate;
        on_unpublish   http://host.docker.internal:5082/api/streaming/end;
        # Viewer hooks
        on_play        http://host.docker.internal:5082/api/streaming/start;
        on_stop        http://host.docker.internal:5082/api/streaming/stop;
    }

    # HTTP-FLV config
    http_remux {
        enabled     on;
        mount       live/[stream].flv;
    }

    # Reduce latency
    dash {
        enabled         off;
    }
    hls {
        enabled         off;
    }
}